#ifndef ERRORS
#define ERRORS

#define INPUT_IMG_NOT_FOUND 1U
#define INPUT_TXT_NOT_FOUND 2U
#define MAX_IMG_FILE_SIZE_EXCEEDED 3U
#define MAX_TXT_FILE_SIZE_EXCEEDED 4U
#define INSUFFICIENT_IMG_SIZE 5U
#define INVALID_IMG_FORMAT 6U
#define INVALID_TXT_FILE 7U
#define ERR_MEMORY_ALLLOC 8U

#endif //ERRORS